"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](red)'
vimcmd_symbol = "[#](white)"
vimcmd_visual_symbol = "[#](bold yellow)"
